/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pizzashop;

//imports
import com.pizzashop.PizzaFormNew;
import com.pizzashop.PizzaFormList;
import javax.swing.JOptionPane;

/**
 *
 * @author Anam Ashraf
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        newPizzaLnk = new javax.swing.JMenu();
        viewPizzaListLnk = new javax.swing.JMenu();
        viewPizzaListLnk1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        newPizzaLnk.setText("New");
        newPizzaLnk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPizzaLnkActionPerformed(evt);
            }
        });
        jMenuBar1.add(newPizzaLnk);

        viewPizzaListLnk.setText("List");
        viewPizzaListLnk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPizzaListLnkActionPerformed(evt);
            }
        });
        jMenuBar1.add(viewPizzaListLnk);

        viewPizzaListLnk1.setText("Update");
        jMenuBar1.add(viewPizzaListLnk1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1233, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newPizzaLnkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPizzaLnkActionPerformed
        JOptionPane.showMessageDialog(null, "Username or Password is wrong");
//        PizzaFormNew newPizzaForm = new PizzaFormNew();
//        newPizzaForm.setVisible(true);
    }//GEN-LAST:event_newPizzaLnkActionPerformed

    private void viewPizzaListLnkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPizzaListLnkActionPerformed
        
//        JOptionPane.showMessageDialog(null, "Username or Password is wrong");
    }//GEN-LAST:event_viewPizzaListLnkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu newPizzaLnk;
    private javax.swing.JMenu viewPizzaListLnk;
    private javax.swing.JMenu viewPizzaListLnk1;
    // End of variables declaration//GEN-END:variables
}
